# Pandas

## Installing Packages

In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\ishaan rastogi\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ishaan rastogi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ishaan rastogi\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ishaan rastogi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\ishaan rastogi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## Importing Libraries

In [2]:
import pandas as pd

## Basics

In [3]:
pd.Series([10, 20, 30, 40, 50, 'abc'])

0     10
1     20
2     30
3     40
4     50
5    abc
dtype: object

In [4]:
s = pd.Series([10, 20, 30, 40, 50,])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
s.dtype

dtype('int64')

In [6]:
s.values

array([10, 20, 30, 40, 50])

In [7]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
s.name = "calories"
s.name

'calories'

In [9]:
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

## Indexing

In [10]:
s[0]

np.int64(10)

In [11]:
s[::2]

0    10
2    30
4    50
Name: calories, dtype: int64

### Location Based Indexing

**NOTE-** Both Start and Stop values are included in the output

In [12]:
# iloc
s.iloc[3]

np.int64(40)

In [13]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: calories, dtype: int64

In [14]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [15]:
s['grapes']

np.int64(30)

In [16]:
# iloc now can't work, we need numbers
# hence loc is used for alphabets

s.loc['grapes']

np.int64(30)

In [17]:
# NOTE- Both Start and Stop values are included in the output
s['banana': 'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

## Conditional Indexing

In [18]:
# dictionary
fruit_protein = {
    "Avocado": 2.0,       # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [19]:
# Creating Series via Dictionary
s2 = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [20]:
# Conditional Selection:
s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

### Logical Operators: and, or, not

In [21]:
s2[(s2>0.5) | (s2 <= 2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [22]:
s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

## Modifying Series

In [23]:
s2["Mango"] = 2.8
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

In [24]:
import numpy as np

In [25]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

## Dataframes

In [26]:
# DataFrame:

data = {
    "Name": ["Alice_Fernandes", "Bob", "Charlie", "David", "Eve", "Alice_Fernandes"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice_Fernandes',
  'Bob',
  'Charlie',
  'David',
  'Eve',
  'Alice_Fernandes'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [27]:
df = pd.DataFrame(data)
df

              Name   Age Department   Salary
0  Alice_Fernandes  25.0         HR  50000.0
1              Bob  30.0         IT  60000.0
2          Charlie  35.0    Finance  70000.0
3            David   NaN         IT  62000.0
4              Eve  29.0         HR      NaN
5  Alice_Fernandes  25.0         HR  50000.0

In [28]:
df.head(2)

              Name   Age Department   Salary
0  Alice_Fernandes  25.0         HR  50000.0
1              Bob  30.0         IT  60000.0

In [29]:
df.tail(3)

              Name   Age Department   Salary
3            David   NaN         IT  62000.0
4              Eve  29.0         HR      NaN
5  Alice_Fernandes  25.0         HR  50000.0

In [30]:
df.iloc[1:3, :2] #rows, columns

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [31]:
df.loc[1:2, ["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance

In [32]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [33]:
df.drop("Age", axis = 1) # if row is to be removed, axis will be 0

              Name Department   Salary
0  Alice_Fernandes         HR  50000.0
1              Bob         IT  60000.0
2          Charlie    Finance  70000.0
3            David         IT  62000.0
4              Eve         HR      NaN
5  Alice_Fernandes         HR  50000.0

In [34]:
df

              Name   Age Department   Salary
0  Alice_Fernandes  25.0         HR  50000.0
1              Bob  30.0         IT  60000.0
2          Charlie  35.0    Finance  70000.0
3            David   NaN         IT  62000.0
4              Eve  29.0         HR      NaN
5  Alice_Fernandes  25.0         HR  50000.0

In [35]:
df.shape

(6, 4)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         5 non-null      float64
 2   Department  6 non-null      str
 3   Salary      5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

In [37]:
df.describe() # 25%, 50%, 75%, max are outliers in our dataset

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [38]:
# Broadcasting
df["Salary"] = df["Salary"] + 5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [39]:
# Renaming Columns
df.rename(columns = {"Department": "Dept"}, inplace = True)

In [40]:
df["Dept"].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [41]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [42]:
df["Promoted Salary"] = df["Salary"] * 10

In [43]:
df

              Name   Age     Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0       HR  55000.0         550000.0
1              Bob  30.0       IT  65000.0         650000.0
2          Charlie  35.0  Finance  75000.0         750000.0
3            David   NaN       IT  67000.0         670000.0
4              Eve  29.0       HR      NaN              NaN
5  Alice_Fernandes  25.0       HR  55000.0         550000.0

## Data Cleaning

In [44]:
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [45]:
df.dropna(how = "any") # any row that had any null value

              Name   Age     Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0       HR  55000.0         550000.0
1              Bob  30.0       IT  65000.0         650000.0
2          Charlie  35.0  Finance  75000.0         750000.0
5  Alice_Fernandes  25.0       HR  55000.0         550000.0

In [46]:
df.dropna(how = "all") #if all the values in any row are null then we drop that row

              Name   Age     Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0       HR  55000.0         550000.0
1              Bob  30.0       IT  65000.0         650000.0
2          Charlie  35.0  Finance  75000.0         750000.0
3            David   NaN       IT  67000.0         670000.0
4              Eve  29.0       HR      NaN              NaN
5  Alice_Fernandes  25.0       HR  55000.0         550000.0

In [47]:
df

              Name   Age     Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0       HR  55000.0         550000.0
1              Bob  30.0       IT  65000.0         650000.0
2          Charlie  35.0  Finance  75000.0         750000.0
3            David   NaN       IT  67000.0         670000.0
4              Eve  29.0       HR      NaN              NaN
5  Alice_Fernandes  25.0       HR  55000.0         550000.0

In [48]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [49]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [50]:
df["Age"].ffill(inplace=True) # forward fill

C:\Users\Ishaan Rastogi\AppData\Local\Temp\ipykernel_1491528\3123493913.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].ffill(inplace=True) # forward fill

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [51]:
df["Age"].bfill(inplace=True) #backward fill

C:\Users\Ishaan Rastogi\AppData\Local\Temp\ipykernel_1491528\1802496660.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].bfill(inplace=True) #backward fill

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [52]:
df["Name"] = df["Name"].replace("Charlie", "Rose")

df

              Name   Age     Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0       HR  55000.0         550000.0
1              Bob  30.0       IT  65000.0         650000.0
2             Rose  35.0  Finance  75000.0         750000.0
3            David   NaN       IT  67000.0         670000.0
4              Eve  29.0       HR      NaN              NaN
5  Alice_Fernandes  25.0       HR  55000.0         550000.0

## Duplicates

In [53]:
# duplicates
df_dup = df[df.duplicated(keep = "last")]
df_dup

              Name   Age Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0   HR  55000.0         550000.0

In [54]:
df = df.drop_duplicates()
df

              Name   Age     Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0       HR  55000.0         550000.0
1              Bob  30.0       IT  65000.0         650000.0
2             Rose  35.0  Finance  75000.0         750000.0
3            David   NaN       IT  67000.0         670000.0
4              Eve  29.0       HR      NaN              NaN

## Lambda Functions

In [55]:
# Lambda -> python

df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)
df

              Name   Age     Dept   Salary  Promoted Salary
0  Alice_Fernandes  25.0       HR  55000.0         550000.0
1              Bob  30.0       IT  65000.0         650000.0
2             Rose  35.0  Finance  75000.0          75000.0
3            David   NaN       IT  67000.0          67000.0
4              Eve  29.0       HR      NaN              NaN

In [56]:
name = "Alice_Fernandes"
df[["first_name", "last_name"]] = df["Name"].str.split("_", expand = True) # expand will set the value after _ to None for those who don't have _
df

,Name,Age,Dept,Salary,Promoted Salary,first_name,last_name
0,Alice_Fernandes,25.0,HR,55000.0,550000.0,Alice,Fernandes
1,Bob,30.0,IT,65000.0,650000.0,Bob,NaN
2,Rose,35.0,Finance,75000.0,75000.0,Rose,NaN
3,David,NaN,IT,67000.0,67000.0,David,NaN
4,Eve,29.0,HR,NaN,NaN,Eve,NaN

In [57]:
# apply and lambda
def multiplying_age(x):
  return x*2

df["Age"] = df["Age"].apply(multiplying_age)
df

,Name,Age,Dept,Salary,Promoted Salary,first_name,last_name
0,Alice_Fernandes,50.0,HR,55000.0,550000.0,Alice,Fernandes
1,Bob,60.0,IT,65000.0,650000.0,Bob,NaN
2,Rose,70.0,Finance,75000.0,75000.0,Rose,NaN
3,David,NaN,IT,67000.0,67000.0,David,NaN
4,Eve,58.0,HR,NaN,NaN,Eve,NaN

In [58]:
df["Age"] = df["Age"].apply(lambda x: x/2)
df

,Name,Age,Dept,Salary,Promoted Salary,first_name,last_name
0,Alice_Fernandes,25.0,HR,55000.0,550000.0,Alice,Fernandes
1,Bob,30.0,IT,65000.0,650000.0,Bob,NaN
2,Rose,35.0,Finance,75000.0,75000.0,Rose,NaN
3,David,NaN,IT,67000.0,67000.0,David,NaN
4,Eve,29.0,HR,NaN,NaN,Eve,NaN

## Joins & Merges

In [59]:
department_info = {
    "Dept": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [60]:
pd.concat([df, df2])

,Name,Age,Dept,Salary,Promoted Salary,first_name,last_name,Location,Manager
0,Alice_Fernandes,25.0,HR,55000.0,550000.0,Alice,Fernandes,NaN,NaN
1,Bob,30.0,IT,65000.0,650000.0,Bob,NaN,NaN,NaN
2,Rose,35.0,Finance,75000.0,75000.0,Rose,NaN,NaN,NaN
3,David,NaN,IT,67000.0,67000.0,David,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,Eve,NaN,NaN,NaN
0,NaN,NaN,HR,NaN,NaN,NaN,NaN,New York,Laura
1,NaN,NaN,IT,NaN,NaN,NaN,NaN,San Francisco,Steve
2,NaN,NaN,Finance,NaN,NaN,NaN,NaN,Chicago,Nina

In [61]:
pd.concat([df, df2], axis = 1) # Common column is repeated

,Name,Age,Dept,Salary,Promoted Salary,first_name,last_name,Dept,Location,Manager
0,Alice_Fernandes,25.0,HR,55000.0,550000.0,Alice,Fernandes,HR,New York,Laura
1,Bob,30.0,IT,65000.0,650000.0,Bob,NaN,IT,San Francisco,Steve
2,Rose,35.0,Finance,75000.0,75000.0,Rose,NaN,Finance,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,David,NaN,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,Eve,NaN,NaN,NaN,NaN

In [62]:
pd.merge(df, df2, on = "Dept") # Merged on the common column Dept

,Name,Age,Dept,Salary,Promoted Salary,first_name,last_name,Location,Manager
0,Alice_Fernandes,25.0,HR,55000.0,550000.0,Alice,Fernandes,New York,Laura
1,Bob,30.0,IT,65000.0,650000.0,Bob,NaN,San Francisco,Steve
2,Rose,35.0,Finance,75000.0,75000.0,Rose,NaN,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,David,NaN,San Francisco,Steve
4,Eve,29.0,HR,NaN,NaN,Eve,NaN,New York,Laura

## Importing a dataset file

In [63]:
data = pd.read_csv(r"C:\Users\Ishaan Rastogi\Desktop\AIML_MiniProjects\datasets\Housing.csv")

In [64]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              545 non-null    str
 1   price             545 non-null    int64
 2   area              545 non-null    int64
 3   bedrooms          545 non-null    int64
 4   bathrooms         545 non-null    int64
 5   stories           545 non-null    int64
 6   mainroad          545 non-null    str
 7   guestroom         545 non-null    str
 8   basement          545 non-null    str
 9   hotwaterheating   545 non-null    str
 10  airconditioning   545 non-null    str
 11  parking           545 non-null    int64
 12  prefarea          545 non-null    str
 13  furnishingstatus  545 non-null    str
dtypes: int64(6), str(8)
memory usage: 59.7 KB

In [65]:
data['date'] = pd.to_datetime(data['date']) # converting date into time

In [66]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              545 non-null    datetime64[us]
 1   price             545 non-null    int64
 2   area              545 non-null    int64
 3   bedrooms          545 non-null    int64
 4   bathrooms         545 non-null    int64
 5   stories           545 non-null    int64
 6   mainroad          545 non-null    str
 7   guestroom         545 non-null    str
 8   basement          545 non-null    str
 9   hotwaterheating   545 non-null    str
 10  airconditioning   545 non-null    str
 11  parking           545 non-null    int64
 12  prefarea          545 non-null    str
 13  furnishingstatus  545 non-null    str
dtypes: datetime64[us](1), int64(6), str(7)
memory usage: 59.7 KB