### Transformation of Features

Why Transformation of Features Are Required?

1. Linear Regression---Gradient Descent ----Global Minima
2. Algorithms like KNN,K Means,Hierarichal Clustering--- Eucledian Distance

Every Point has some vectors and Directiom

Deep Learning Techniques(Standardization, Scaling)
1.ANN--->GLobal Minima, Gradient
2.CNN
3.RNN

0-255 pixels

#### Types Of Transformation
1. Normalization And Standardization
2. Scaling to Minimum And Maximum values
3. Scaling To Median And Quantiles
4. Guassian Transformation
5. Logarithmic Transformation
6. Reciprocal Trnasformation
7. Square Root Transformation
8. Exponential Trnasformation
9. Box Cox Transformation

##### Standardization(Why standardization?)
Standardization comes into picture when features of input data set have large differences between their ranges, or simply when they are measured in different measurement units (e.g., Pounds, Meters, Miles … etc).

We try to bring all the variables or features to a similar scale. standarisation means centering the variable at zero.
z=(x-x_mean)/std

In [1]:
%pip install uv
%uv venv
%uv pip install -r requirements.txt

Requirement already satisfied: uv in c:\users\ishaan rastogi\appdata\local\programs\python\python313\lib\site-packages (0.11.8)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

Using CPython 3.13.1 interpreter at: C:\Users\Ishaan Rastogi\AppData\Local\Programs\Python\Python313\python.exe
Creating virtual environment at: .venv
error: Failed to create virtual environment
  Caused by: A virtual environment already exists at `.venv`. Use `--clear` to replace it

Note: you may need to restart the kernel to use updated packages.

Using Python 3.13.1 environment at: C:\Users\Ishaan Rastogi\AppData\Local\Programs\Python\Python313
Checked 9 packages in 39ms

In [17]:
import pandas as pd
df=pd.read_csv("datasets/titanic.csv", usecols=['Pclass','Age','Fare','Survived'])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [3]:
df['Age'].fillna(df.Age.median(),inplace=True)

C:\Users\Ishaan Rastogi\AppData\Local\Temp\ipykernel_2425816\2569459057.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df.Age.median(),inplace=True)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [4]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
Fare          0
dtype: int64

In [5]:
### Independent and dependent features
X=df.iloc[:,1:]
y=df.iloc[:,0]

In [6]:
X

     Pclass   Age     Fare
0         3  22.0   7.2500
1         1  38.0  71.2833
2         3  26.0   7.9250
3         1  35.0  53.1000
4         3  35.0   8.0500
..      ...   ...      ...
886       2  27.0  13.0000
887       1  19.0  30.0000
888       3   NaN  23.4500
889       1  26.0  30.0000
890       3  32.0   7.7500

[891 rows x 3 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
X_train

     Pclass   Age      Fare
6         1  54.0   51.8625
718       3   NaN   15.5000
685       2  25.0   41.5792
73        3  26.0   14.4542
882       3  22.0   10.5167
..      ...   ...       ...
106       3  21.0    7.6500
270       1   NaN   31.0000
860       3  41.0   14.1083
435       1  14.0  120.0000
102       1  21.0   77.2875

[596 rows x 3 columns]

In [ ]:
#### standarisation: We use the Standardscaler from sklearn library
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
### fit vs fit_transform - fit_transform is combination of fit and transform. It first fits the data by computing the mean and standard deviation, and then transforms it.
X_train_scaled=scaler.fit_transform(X_train)

In [11]:
X_train_scaled

array([[-1.62580285,  1.69460589,  0.38784185],
       [ 0.80576177,         nan, -0.31908053],
       [-0.41002054, -0.3133837 ,  0.18792449],
       ...,
       [ 0.80576177,  0.79447262, -0.34613654],
       [-1.62580285, -1.07503492,  1.71250117],
       [-1.62580285, -0.59034778,  0.8821286 ]], shape=(596, 3))

In [12]:
X_test_scaled=scaler.transform(X_test)

In [13]:
X_test_scaled

array([[ 0.80576177,         nan, -0.32402243],
       [-0.41002054,  0.10206242, -0.4162854 ],
       [ 0.80576177, -0.6595888 , -0.46634591],
       [-0.41002054, -1.62896308,  0.0211365 ],
       [ 0.80576177, -1.07503492, -0.40186603],
       [-1.62580285, -0.24414268,  0.91250512],
       [ 0.80576177,         nan, -0.46974808],
       [ 0.80576177, -0.93655288, -0.2704781 ],
       [ 0.80576177, -0.93655288, -0.46974808],
       [-1.62580285, -0.72882982, -0.10944269],
       [-1.62580285,  0.51750854,  0.41190006],
       [ 0.80576177,  1.00219569, -0.46391578],
       [ 0.80576177,         nan, -0.12531819],
       [ 0.80576177,  0.0328214 , -0.47995459],
       [-0.41002054,  0.44826752, -0.36768297],
       [-1.62580285, -0.93655288,  0.14555873],
       [-1.62580285,  0.86371365,  0.40128918],
       [ 0.80576177,         nan, -0.46820835],
       [-0.41002054, -0.17490166, -0.36768297],
       [-1.62580285,  1.20991875,  0.39051499],
       [ 0.80576177, -0.38262472, -0.46691358],
       [-1.62580285,  0.30978548, -0.10425778],
       [ 0.80576177, -0.72882982, -0.46772233],
       [ 0.80576177, -0.6595888 , -0.44107264],
       [ 0.80576177,         nan, -0.33852151],
       [ 0.80576177, -1.351999  , -0.07801247],
       [-1.62580285,  0.7252316 , -0.08149629],
       [-0.41002054,  0.10206242, -0.36768297],
       [ 0.80576177, -1.76744512, -0.07801247],
       [ 0.80576177,  0.10206242, -0.46772233],
       [ 0.80576177, -0.72882982, -0.46691358],
       [ 0.80576177, -0.52110676, -0.46974808],
       [-1.62580285,         nan, -0.02365939],
       [ 0.80576177,         nan, -0.47363627],
       [ 0.80576177, -0.79807084, -0.46391578],
       [ 0.80576177, -0.17490166, -0.3394119 ],
       [-1.62580285, -0.10566064,  0.06973893],
       [ 0.80576177,         nan, -0.46974808],
       [-1.62580285,  0.0328214 , -0.01774545],
       [ 0.80576177,         nan, -0.46691358],
       [-0.41002054, -0.59034778,  0.80849591],
       [ 0.80576177, -0.03641962, -0.48343841],
       [ 0.80576177,         nan, -0.46391578],
       [ 0.80576177,         nan, -0.46974808],
       [ 0.80576177,  1.07143671, -0.3394119 ],
       [ 0.80576177, -0.93655288,  0.04786783],
       [ 0.80576177, -0.72882982, -0.46181033],
       [ 0.80576177, -0.45186574, -0.44107264],
       [ 0.80576177, -0.38262472, -0.48335676],
       [-1.62580285,  1.97156997,  1.58176062],
       [ 0.80576177, -1.6982041 , -0.24601552],
       [-1.62580285,  1.55612385,  1.19731538],
       [ 0.80576177,  0.7252316 , -0.07801247],
       [-1.62580285, -1.28275798,  1.71250117],
       [ 0.80576177,  2.45625711, -0.46974808],
       [-1.62580285, -0.79807084,  0.9280579 ],
       [-0.41002054,  0.17130344, -0.4162854 ],
       [-1.62580285,  1.41764181,  4.19162962],
       [-0.41002054,  0.3790265 , -0.21215518],
       [ 0.80576177, -0.72882982, -0.4672363 ],
       [ 0.80576177, -0.59034778, -0.46926205],
       [-0.41002054, -1.14427594, -0.24131664],
       [-0.41002054, -0.10566064, -0.11495032],
       [-1.62580285,         nan, -0.11640839],
       [ 0.80576177,         nan, -0.46974808],
       [-0.41002054,  1.90232895, -0.4162854 ],
       [-0.41002054, -0.59034778,  0.80849591],
       [ 0.80576177, -0.03641962, -0.46731796],
       [ 0.80576177, -0.86731186, -0.47987294],
       [-1.62580285,  1.55612385,  0.9011652 ],
       [-0.41002054, -0.24414268, -0.11495032],
       [-1.62580285, -0.79807084,  4.48040973],
       [-1.62580285, -0.24414268, -0.03718642],
       [-1.62580285,  0.65599058,  0.99626266],
       [ 0.80576177, -0.45186574, -0.46772233],
       [ 0.80576177,  0.44826752, -0.31810849],
       [ 0.80576177,  0.06744191, -0.46974808],
       [-1.62580285, -0.52110676,  0.34191255],
       [-0.41002054,  0.58674956, -0.36768297],
       [ 0.80576177,  0.79447262, -0.22746495],
       [ 0.80576177, -0.93655288,  0.15114801],
       [-0.41002054, -0.03641962, -0.4162854 ],
       [-1.62580285,  0.7252316 ,  1.99439528],
       [ 0.80576177,         nan, -0.46999109],
       [-1.62580285,  1.83308793, -0.02365939],
       [-1.62580285,  2.87170323,  0.34199421],
       [-1.62580285,  0.10206242,  1.58176062],
       [-1.62580285,  0.0328214 ,  0.48634343],
       [-1.62580285,  0.58674956, -0.62041562],
       [ 0.80576177,         nan, -0.47946856],
       [ 0.80576177, -1.42124002, -0.22138964],
       [ 0.80576177, -1.42124002, -0.01239918],
       [-1.62580285,  2.17929303,  0.00793219],
       [ 0.80576177,         nan, -0.47015245],
       [ 0.80576177,         nan, -0.46691358],
       [ 0.80576177, -0.10566064, -0.46772233],
       [-1.62580285,  1.27915977,  0.39051499],
       [ 0.80576177,  1.07143671, -0.46391578],
       [-0.41002054,  0.44826752, -0.36768297],
       [ 0.80576177, -0.17490166, -0.46691358],
       [-1.62580285,  2.38701609, -0.11495032],
       [ 0.80576177,  0.3790265 , -0.48189869],
       [-1.62580285, -0.72882982,  1.15025267],
       [ 0.80576177,  0.58674956, -0.48335676],
       [ 0.80576177,  0.06744191, -0.46391578],
       [ 0.80576177, -0.3133837 , -0.46926205],
       [-0.41002054,  0.7252316 ,  0.13778234],
       [-1.62580285,  1.20991875,  0.12806185],
       [ 0.80576177,  0.0328214 , -0.43572637],
       [-1.62580285,  0.7252316 , -0.01774545],
       [-1.62580285,         nan,  0.39051499],
       [ 0.80576177, -0.62496829, -0.47946856],
       [-1.62580285,         nan,  1.11185675],
       [-1.62580285,  0.44826752, -0.10936104],
       [-1.62580285,         nan,  3.69118787],
       [ 0.80576177, -0.6595888 , -0.42900369],
       [-1.62580285,  2.87170323,  0.05329575],
       [-0.41002054,  0.44826752, -0.37011309],
       [-0.41002054, -0.52110676, -0.0566274 ],
       [ 0.80576177,  1.27915977,  0.04786783],
       [-0.41002054, -0.45186574, -0.39684443],
       [-1.62580285,  0.17130344,  0.86276928],
       [-1.62580285,  2.31777507,  0.8951696 ],
       [-0.41002054, -1.98693916, -0.0566274 ],
       [ 0.80576177, -0.3133837 , -0.47946856],
       [-1.62580285,  0.3790265 , -0.10425778],
       [-1.62580285,  1.34840079, -0.11632674],
       [-1.62580285, -0.38262472,  0.91930946],
       [ 0.80576177,         nan, -0.3393322 ],
       [ 0.80576177, -0.59034778, -0.46391578],
       [ 0.80576177,         nan, -0.4672363 ],
       [ 0.80576177,         nan, -0.32402243],
       [-0.41002054,         nan, -0.62041562],
       [ 0.80576177, -1.6982041 , -0.37788948],
       [-1.62580285,  1.34840079,  0.48634343],
       [ 0.80576177, -1.0057939 , -0.3394119 ],
       [-1.62580285,         nan,  1.53526365],
       [ 0.80576177, -0.03641962, -0.46926205],
       [ 0.80576177,  0.86371365, -0.47363627],
       [ 0.80576177, -0.79807084, -0.2743663 ],
       [ 0.80576177, -0.59034778, -0.45646406],
       [-0.41002054,  1.00219569, -0.11495032],
       [-0.41002054, -0.10566064, -0.36768297],
       [-0.41002054,  0.51750854, -0.11495032],
       [ 0.80576177,  0.65599058, -0.05419727],
       [-0.41002054,  0.30978548,  0.01141601],
       [-0.41002054,  0.0328214 , -0.36768297],
       [-0.41002054,  2.52549813, -0.4162854 ],
       [-1.62580285,         nan,  2.22809133],
       [ 0.80576177,  0.93295467, -0.46391578],
       [ 0.80576177,         nan, -0.45103614],
       [ 0.80576177, -0.38262472, -0.47468997],
       [ 0.80576177, -0.79807084, -0.46885768],
       [ 0.80576177,         nan, -0.15091612],
       [ 0.80576177,         nan, -0.46391578],
       [ 0.80576177,         nan, -0.48335676],
       [ 0.80576177,         nan,  0.47791772],
       [ 0.80576177,         nan, -0.46901904],
       [-0.41002054,  0.44826752, -0.11495032],
       [ 0.80576177,  0.17130344, -0.31908053],
       [ 0.80576177, -0.41724523, -0.47987294],
       [-1.62580285,         nan, -0.10425778],
       [-0.41002054,  0.65599058, -0.36768297],
       [-1.62580285,         nan,  0.9770647 ],
       [ 0.80576177,         nan, -0.45597804],
       [-1.62580285,  2.45625711,  0.58452035],
       [-0.41002054, -0.45186574, -0.4162854 ],
       [-1.62580285,         nan,  0.38784185],
       [ 0.80576177, -0.52110676, -0.46691358],
       [ 0.80576177,  0.3790265 , -0.48335676],
       [-1.62580285, -0.45186574,  0.61133139],
       [-0.41002054, -0.79807084, -0.36768297],
       [-1.62580285,  0.44826752, -0.10741694],
       [ 0.80576177, -1.42124002, -0.32402243],
       [ 0.80576177, -0.86731186, -0.48189869],
       [ 0.80576177,         nan, -0.47995459],
       [ 0.80576177,  0.58674956, -0.01021207],
       [-0.41002054, -0.86731186, -0.4162854 ],
       [ 0.80576177, -1.76744512, -0.29575137],
       [-1.62580285,  1.10605722, -0.06634788],
       [-0.41002054, -0.45186574, -0.36768297],
       [ 0.80576177,  0.17130344, -0.46634591],
       [ 0.80576177, -0.24414268, -0.46772233],
       [ 0.80576177, -1.62896308, -0.01239918],
       [-1.62580285, -0.38262472,  4.19162962],
       [-1.62580285,  1.07143671, -0.10425778],
       [-0.41002054, -0.03641962, -0.08149629],
       [ 0.80576177,         nan, -0.46691358],
       [-1.62580285,         nan,  0.06973893],
       [-0.41002054,  0.86371365, -0.36768297],
       [ 0.80576177,  0.44826752, -0.15091612],
       [-0.41002054,  0.24054446, -0.38177767],
       [ 0.80576177, -0.86731186, -0.48327511],
       [ 0.80576177, -0.03641962, -0.43572637],
       [-0.41002054,  1.41764181, -0.11495032],
       [-1.62580285,  0.3790265 ,  1.12927197],
       [-1.62580285,  0.58674956,  3.80289181],
       [-0.41002054,  0.30978548, -0.36768297],
       [-1.62580285, -0.86731186,  0.48771985],
       [ 0.80576177, -1.28275798, -0.01239918],
       [ 0.80576177,  2.17929303, -0.49915255],
       [ 0.80576177,  0.0328214 , -0.45200819],
       [-0.41002054, -1.55972206, -0.11009007],
       [ 0.80576177,  2.31777507, -0.43402529],
       [ 0.80576177, -0.6595888 , -0.47987294],
       [ 0.80576177,         nan, -0.18574851],
       [ 0.80576177, -0.03641962, -0.43605104],
       [-1.62580285,  0.44826752,  1.71250117],
       [ 0.80576177,         nan, -0.3393322 ],
       [ 0.80576177,  1.41764181, -0.46391578],
       [-1.62580285, -0.17490166,  3.49135022],
       [ 0.80576177,  0.0328214 , -0.47946856],
       [-1.62580285,  0.24054446,  1.12927197],
       [ 0.80576177,         nan, -0.4702341 ],
       [ 0.80576177,         nan, -0.12531819],
       [ 0.80576177, -1.90592716, -0.21069711],
       [-0.41002054, -0.3133837 , -0.03718642],
       [-1.62580285,  1.48688283,  0.57285576],
       [-0.41002054, -0.3133837 , -0.11495032],
       [ 0.80576177,         nan, -0.47946856],
       [ 0.80576177,         nan, -0.46691358],
       [-0.41002054, -0.38262472, -0.36768297],
       [ 0.80576177, -0.79807084, -0.22746495],
       [-1.62580285,         nan, -0.02746594],
       [ 0.80576177, -0.3133837 , -0.48335676],
       [-0.41002054, -0.38262472, -0.33852151],
       [ 0.80576177, -0.52110676, -0.47420395],
       [-1.62580285, -1.98070747,  2.32586387],
       [-0.41002054, -0.38262472, -0.11495032],
       [ 0.80576177, -0.24414268, -0.46634591],
       [-0.41002054,  0.30978548, -0.21215518],
       [-1.62580285, -0.59034778,  4.48040973],
       [ 0.80576177,         nan, -0.46974808],
       [ 0.80576177,         nan, -0.47987294],
       [ 0.80576177,         nan, -0.45200819],
       [ 0.80576177, -0.52110676, -0.46926205],
       [-1.62580285,  2.24853405,  0.93486224],
       [ 0.80576177, -0.79807084, -0.42908339],
       [-1.62580285,  0.86371365,  3.80289181],
       [-0.41002054,  1.90232895, -0.3803196 ],
       [ 0.80576177, -0.72882982, -0.62041562],
       [-0.41002054,  0.86371365, -0.11495032],
       [ 0.80576177,         nan, -0.47995459],
       [ 0.80576177, -0.6595888 , -0.45200819],
       [ 0.80576177,  0.34440599, -0.49526435],
       [ 0.80576177, -0.10566064, -0.43572637],
       [ 0.80576177,         nan, -0.46391578],
       [ 0.80576177, -0.45186574, -0.46691358],
       [ 0.80576177, -0.52110676, -0.47946856],
       [-1.62580285,  1.55612385, -0.02746594],
       [ 0.80576177,  0.0328214 , -0.37788948],
       [-0.41002054,  0.48288803, -0.11495032],
       [ 0.80576177,         nan, -0.46974808],
       [ 0.80576177, -0.52110676, -0.47987294],
       [-1.62580285,  1.41764181,  1.97787045],
       [ 0.80576177, -0.17490166, -0.48481483],
       [ 0.80576177, -0.52110676, -0.46391578],
       [-1.62580285,  1.48688283,  0.8951696 ],
       [-0.41002054,  0.44826752, -0.4162854 ],
       [-0.41002054, -0.03641962, -0.11495032],
       [-1.62580285, -0.52110676,  2.32586387],
       [-1.62580285,  1.41764181,  1.44858996],
       [-0.41002054,  0.7252316 , -0.36768297],
       [ 0.80576177, -0.17490166, -0.45200819],
       [-1.62580285,         nan, -0.62041562],
       [-1.62580285,  2.45625711, -0.10425778],
       [ 0.80576177, -0.86731186, -0.45200819],
       [-1.62580285, -0.10566064, -0.10425778],
       [-1.62580285, -1.76744512,  0.9709894 ],
       [ 0.80576177,         nan, -0.46691358],
       [ 0.80576177, -1.97516818, -0.40397343],
       [-0.41002054,  0.44826752, -0.08092861],
       [-0.41002054,  0.93295467, -0.11009007],
       [-1.62580285,  0.58674956,  2.36304473],
       [-0.41002054,  0.10206242, -0.11009007],
       [ 0.80576177, -0.03641962, -0.46391578],
       [ 0.80576177, -0.79807084, -0.45905554],
       [-0.41002054,         nan, -0.32782897],
       [-1.62580285,  0.65599058,  1.53526365],
       [-0.41002054,  0.65599058, -0.36768297],
       [ 0.80576177, -0.24414268, -0.45200819],
       [ 0.80576177, -0.6595888 , -0.48335676],
       [-1.62580285,         nan,  1.97787045],
       [ 0.80576177,  1.34840079, -0.62041562],
       [-0.41002054, -0.45186574, -0.32791062],
       [ 0.80576177, -1.97516818,  0.15114801],
       [ 0.80576177,         nan, -0.4672363 ],
       [ 0.80576177,         nan, -0.1645248 ],
       [-0.41002054, -1.83668614, -0.11495032],
       [ 0.80576177, -1.76744512, -0.40397343],
       [ 0.80576177, -0.72882982, -0.47169217],
       [ 0.80576177,  0.75985211, -0.46974808],
       [ 0.80576177, -1.97516818, -0.31438165],
       [ 0.80576177,         nan, -0.32402243],
       [ 0.80576177, -0.59034778, -0.46634591]])

In [14]:
### Model Building
## fit() for training and predict for test

In [15]:
from sklearn.linear_model import LogisticRegression
classification=LogisticRegression()

In [16]:
classification.fit(X_train_scaled,y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
classification.predict(X_test_scaled)

In [ ]:
df_scaled=df_scaled.transform(df)

In [ ]:
df_scaled

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df_scaled

In [ ]:
plt.hist(df_scaled[:,1],bins=20)

In [ ]:
plt.hist(df_scaled[:,2],bins=20)

In [ ]:
plt.hist(df_scaled[:,3],bins=20)

In [ ]:
plt.hist(df['Fare'],bins=20)

##### Min Max Scaling  (### CNN)---Deep Learning Techniques
Min Max Scaling scales the values between 0 to 1.
X_scaled = (X - X.min / (X.max - X.min)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
df_minmax=pd.DataFrame(min_max.fit_transform(X_train))
df_minmax.head()

In [ ]:
sns.pairplot(df_minmax)

In [ ]:
plt.hist(df_minmax['Pclass'],bins=20)

In [ ]:
plt.hist(df_minmax['Age'],bins=20)

In [ ]:
plt.hist(df_minmax['Fare'],bins=20)

##### Robust Scaler
Robust Scaler are robust to outliers.It is used to scale the feature to median and quantiles
Scaling using median and quantiles consists of substracting the median to all the observations, and then dividing by the interquantile difference. The interquantile difference is the difference between the 75th and 25th quantile:

IQR = 75th quantile - 25th quantile

X_scaled = (X - X.median) / IQR

0,1,2,3,4,5,6,7,8,9,10

9-90 percentile---90% of all values in this group is less than 9
1-10 precentile---10% of all values in this group is less than 1
4-40%

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
df_robust_scaler=pd.DataFrame(scaler.fit_transform(X_train))
df_robust_scaler.head()

In [ ]:
scaler.transform(X_test)

In [ ]:
import seaborn as sns
sns.pairplot(df_robust_scaler)

In [ ]:
import seaborn as sns
sns.pairplot(df)

In [ ]:
plt.hist(df_robust_scaler['Age'],bins=20)

In [ ]:
plt.hist(df_robust_scaler['Fare'],bins=20)

#### Guassian Transformation

Some machine learning algorithms like linear and logistic assume that the features are normally distributed
-Accuracy
-Performance
- logarithmic transformation
- reciprocal transformation
- square root transformation
- exponential transformation (more general, you can use any exponent)
- boxcox transformation

In [ ]:
df=pd.read_csv('titanic.csv',usecols=['Age','Fare','Survived'])
df.head()

In [ ]:
### fillnan
df['Age']=df['Age'].fillna(df['Age'].median())

In [ ]:
df.isnull().sum()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import scipy.stats as stat
import pylab

In [ ]:
#### If you want to check whether feature is guassian or normal distributed
#### Q-Q plot
def plot_data(df,feature):
    plt.figure(figsize=(10,6))
    plt.subplot(1,2,1)
    df[feature].hist()
    plt.subplot(1,2,2)
    stat.probplot(df[feature],dist='norm',plot=pylab)
    plt.show()

In [ ]:
plot_data(df,'Age')

#### Logarithmic Transformation

In [ ]:
import numpy as np
df['Age_log']=np.log(df['Age'])
plot_data(df,'Age_log')

#### Reciprocal Trnasformation

In [ ]:
df['Age_reciprocal']=1/df.Age
plot_data(df,'Age_reciprocal')

In [ ]:
##### Square Root Transformation
df['Age_sqaure']=df.Age**(1/2)
plot_data(df,'Age_sqaure')

In [ ]:
#### Exponential Transdormation
df['Age_exponential']=df.Age**(1/1.2)
plot_data(df,'Age_exponential')

#### BoxCOx Transformation
The Box-Cox transformation is defined as: 

T(Y)=(Y exp(λ)−1)/λ

where Y is the response variable and λ is the transformation parameter. λ varies from -5 to 5. In the transformation, all values of λ  are considered and the optimal value for a given variable is selected.

In [ ]:
df['Age_Boxcox'],parameters=stat.boxcox(df['Age'])

In [ ]:
print(parameters)

In [ ]:
plot_data(df,'Age_Boxcox')

In [ ]:
plot_data(df,'Fare')

In [ ]:
#### Fare
df['Fare_log']=np.log1p(df['Fare'])
plot_data(df,'Fare_log')

In [ ]:
df['Fare_Boxcox'],parameters=stat.boxcox(df['Fare']+1)
plot_data(df,'Fare_Boxcox')